---
branches:
  - main
  - master

plugins:
  # commit analyzer
  - - '@semantic-release/commit-analyzer'
    - preset: angular
      releaseRules:
        - breaking: true
          release: major
        - type: docs
          release: false
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: revert
          release: patch
        - type: style
          release: patch
        - type: test
          release: patch
        - type: ci
          release: false
        - type: build
          release: false

  # notes generator
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: breaking
            section: ❗ Breaking ❗
            hidden: false
          - type: feat
            section: ✨ Feature ✨
            hidden: false
          - type: fix
            section: 🐛 Bugfix 🐛
            hidden: false
          - type: ci
            section: 💿 Continuous Integration 💿
            hidden: false
          - type: chore
            section: Chore
            hidden: true
          - type: style
            section: 🖌️ Style 🖌️
            hidden: false
          - type: test
            section: 🧪 Test 🧪
            hidden: false
          - type: docs
            section: 📖 Documentation 📖
            hidden: false
          - type: perf
            section: ️🏎 Performance Improvements 🏎
            hidden: false
          - type: build
            section: 🏗️ Build 🏗️
            hidden: false
          - type: revert
            section: 🔙 Reverts 🔙
            hidden: false

  # changelog
  - - '@semantic-release/changelog'
    - changelogTitle: '# Changelog'

  # npm
  - - '@semantic-release/npm'
    - npmPublish: false

  # exec
  - - '@semantic-release/exec'
    - prepareCmd: 'sh ./semrel-prepare.sh "${nextRelease.version}"'

  # git
  - - '@semantic-release/git'
    - message: 'chore(release): ${nextRelease.version}'
      assets:
        - CHANGELOG.md
        - VERSION
        - package.json
        - package-lock.json

  # github
  - '@semantic-release/github'
