---
name: Production Deployment

on:
  workflow_dispatch:

env:
  FONT_AWESOME_NPM_TOKEN: ${{ secrets.FONT_AWESOME_NPM_TOKEN }}

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v6
      - name: Setup node lts
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          # cache: pnpm # see https://github.com/vercel/vercel/discussions/7581 & https://github.com/actions/cache/issues/319
      - name: Pull Vercel Environment Information
        run: npx vercel env pull --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Run pnpm install
        run: pnpm install
      - name: Run pnpm prebuild
        run: pnpm run prebuild
      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @genaumann/semantic-release-next-sitemap
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
            @semantic-release/github
            conventional-changelog-conventionalcommits@9.3.1

        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
  merge-prod:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: main
      - name: Merge branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch --unshallow
          git checkout prod
          git merge --ff-only main
          git push origin prod
